--- #YAML:1.0
name:               Bookmarks-Parser
version:            0.03
abstract:           A class to parse and represent collections of bookmarks.
author:
    - Marcus Ramberg <mramberg@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::TreeBuilder:  0
    Net::Delicious:     0
    Test::More:         0
    WWW::A9Toolbar:     0
    XML::Simple:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
