# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bookmarks-Parser
version:      0.01
version_from: lib/Bookmarks/Parser.pm
installdirs:  site
requires:
    HTML::TreeBuilder:             0
    Net::Delicious:                0
    Test::More:                    0
    WWW::A9Toolbar:                0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
