---
abstract: 'A class to parse and represent collections of bookmarks.'
author:
  - 'Marcus Ramberg <mramberg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bookmarks-Parser
no_index:
  directory:
    - t
    - inc
requires:
  HTML::TreeBuilder: 0
  Net::Delicious: 0
  Test::More: 0
  WWW::A9Toolbar: 0
  XML::Simple: 0
version: 0.07
